spring:
  profiles:
    active: mac # 기본 환경 선택
---
spring:
  profiles: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: class_a
    password: delab
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  tomcat:
    additional-tld-skip-patterns: orai18n-*.jar
---
spring:
  profiles: mac
  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hivernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console