spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: class_a
    password: delab
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  tomcat:
    additional-tld-skip-patterns: orai18n-*.jar